import { StyleSheet } from 'react-native';

import { Theme } from '../../constants/theme';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Theme.spacing.md,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Theme.colors.background.card,
    alignItems: 'center',
    justifyContent: 'center',
    ...Theme.shadow.small,
  },
  title: {
    fontSize: Theme.typography.size.h3,
    lineHeight: Theme.typography.lineHeight.h3,
    fontWeight: Theme.typography.fontWeight.semibold,
    color: Theme.colors.text.primary,
    marginLeft: Theme.spacing.md,
  },
  subtitle: {
    fontSize: Theme.typography.size.xs,
    lineHeight: Theme.typography.lineHeight.caption,
    color: Theme.colors.text.secondary,
    paddingHorizontal: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
  },
  summaryCard: {
    marginBottom: Theme.spacing.lg,
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background.accentSoftGreen,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  treatmentCard: {
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background.card,
    borderWidth: 1,
    borderColor: Theme.colors.border.default,
    marginBottom: Theme.spacing.md,
    ...Theme.shadow.small,
  },
  treatmentHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  treatmentLabel: {
    fontSize: Theme.typography.size.caption,
    lineHeight: Theme.typography.lineHeight.caption,
    color: Theme.colors.text.secondary,
    fontWeight: Theme.typography.fontWeight.medium,
  },
  treatmentTitle: {
    fontSize: Theme.typography.size.body,
    lineHeight: Theme.typography.lineHeight.body,
    color: Theme.colors.text.primary,
    fontWeight: Theme.typography.fontWeight.semibold,
    marginTop: 2,
  },
  treatmentInfo: {
    fontSize: Theme.typography.size.small,
    lineHeight: Theme.typography.lineHeight.small,
    color: Theme.colors.text.secondary,
    marginTop: Theme.spacing.sm,
  },
  dayBadge: {
    borderRadius: Theme.radius.sm,
    backgroundColor: Theme.colors.background.soft,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.xs,
    marginLeft: Theme.spacing.md,
  },
  dayBadgeText: {
    fontSize: Theme.typography.size.caption,
    lineHeight: Theme.typography.lineHeight.caption,
    color: Theme.colors.text.badge,
    fontWeight: Theme.typography.fontWeight.semibold,
  },
  progressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: Theme.colors.border.default,
    marginTop: Theme.spacing.md,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: Theme.colors.status.success,
  },
  summaryLabel: {
    color: Theme.colors.background.neutralWhite,
    fontSize: Theme.typography.size.xs,
    lineHeight: Theme.typography.lineHeight.caption,
    fontWeight: Theme.typography.fontWeight.medium,
  },
  summaryValue: {
    color: Theme.colors.text.inverted,
    fontSize: Theme.typography.size.h2,
    lineHeight: Theme.typography.lineHeight.h2,
    fontWeight: Theme.typography.fontWeight.semibold,
    marginTop: 2,
  },
  summaryRight: {
    alignItems: 'flex-end',
  },
  sectionLabel: {
    fontSize: Theme.typography.size.caption,
    lineHeight: Theme.typography.lineHeight.caption,
    fontWeight: Theme.typography.fontWeight.semibold,
    color: Theme.colors.text.secondary,
    letterSpacing: 1,
    marginTop: Theme.spacing.sm,
    marginBottom: Theme.spacing.sm,
    textTransform: 'uppercase',
  },
  list: {
    paddingBottom: Theme.spacing.xxxl,
  },
  scheduleDate: {
    fontSize: Theme.typography.size.caption,
    lineHeight: Theme.typography.lineHeight.caption,
    color: Theme.colors.text.secondary,
    fontWeight: Theme.typography.fontWeight.semibold,
    marginTop: Theme.spacing.sm,
    marginBottom: Theme.spacing.sm,
    textTransform: 'uppercase',
  },
  scheduleCard: {
    backgroundColor: Theme.colors.background.card,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border.default,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  scheduleName: {
    fontSize: Theme.typography.size.small,
    lineHeight: Theme.typography.lineHeight.small,
    color: Theme.colors.text.primary,
    fontWeight: Theme.typography.fontWeight.semibold,
  },
  scheduleDose: {
    fontSize: Theme.typography.size.xs,
    lineHeight: Theme.typography.lineHeight.caption,
    color: Theme.colors.text.secondary,
    marginTop: 2,
  },
  scheduleMeta: {
    alignItems: 'flex-end',
    marginLeft: Theme.spacing.md,
  },
  scheduleTime: {
    fontSize: Theme.typography.size.small,
    lineHeight: Theme.typography.lineHeight.small,
    color: Theme.colors.text.primary,
    fontWeight: Theme.typography.fontWeight.medium,
  },
  scheduleStatus: {
    fontSize: Theme.typography.size.caption,
    lineHeight: Theme.typography.lineHeight.caption,
    color: Theme.colors.text.secondary,
    marginTop: 2,
  },
  scheduleStatusTaken: {
    color: Theme.colors.status.success,
    fontWeight: Theme.typography.fontWeight.semibold,
  },
  toggleButton: {
    minHeight: 48,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Theme.spacing.lg,
    paddingHorizontal: Theme.spacing.lg,
  },
  toggleButtonText: {
    fontSize: Theme.typography.size.small,
    lineHeight: Theme.typography.lineHeight.small,
    color: Theme.colors.text.inverted,
    fontWeight: Theme.typography.fontWeight.semibold,
  },
});
